### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by ghost** [chingu-voyage6/Geckos-Team-18-corrupted#1]
We still need to decide on the project name

**Comment by ghost** [comment]
Friscard - Frisky, playful card

**Comment by nuagesdencre** [comment]
I really like it! Throwing more suggestions: Circulate? Pirouette?

**Comment by nuagesdencre** [comment]
Breezy (Cards) - in a breeze
Easily; handily; without much or any effort. Enjoying the benefit of a week off between games, the home team won this match in a breeze.

Link between easy + movement of the pinwheel like pushed by a breeze

**Comment by ghost** [comment]
BreezyCards it is!
