### ISSUE TITLE
Personalize README.md

### ISSUE THREAD

**Issue by ghost** [chingu-voyage6/Geckos-Team-18-corrupted#16]

**Comment by nuagesdencre** [comment]
Suggested format for our little blurb? :) short and sweet?
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e74d40b9f140012131256/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51a17a7584e671e9102f550d5a48ac41590910fdad802cf4a42062c80d55b98e30063e937f03a6aa8318b500bf22824d83b0be8b45c4e13c37aa.PNG)

**Comment by ghost** [comment]
Should the stories be true? :D

**Comment by nuagesdencre** [comment]
make-believe stories are even better!
