### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by ghost** [chingu-voyage6/Geckos-Team-18-corrupted#2]
Create a logo for our app, something to do with cards or collections of cards?

**Comment by nuagesdencre** [comment]
Suggestion #1: pinwheel logo
(working on other ideas as well!)

Colours theme not determined yet.

![chingu_tentative_logo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e74d40b9f140012131256/125516c66e82c728ace21e0d46eb9c932d8596969becb157a549f9822c792b7c2e0be1673295f127b54778154d555ca913590a15a9f08f29a2b26e758c5c0bec87395e20cf3a43bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8d463f1b021088fb5a30a58b06.png)

**Comment by nuagesdencre** [comment]
2nd version - hopefully you'll like 1 or 2 of the lot :)
![Artboard 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e74d40b9f140012131256/125516c66e82c728ace21e0d46c9868e218d82bb8ba9ed01e81fe086264c22703d46f9692587b22dbe4722575d5b4afe445e5f44fdafdd2af2bf3b22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a87bfbd8c4ac0ec3d27e58b9d02.png)

**Comment by nuagesdencre** [comment]
![chingu_pinwheel_logo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e74d40b9f140012131256/125516c66e82c728ace21e0d46eb9c932d8596969fe0b154ac58f598164a28742646ef696097ec22ba416f43554d4bfe400d0e11f5ff8b2fa2e439768a5c0abb856c0b7dc16f03b0aac04ee155e57dd205d0f4ae805ec2e83724e289864a3d19021f8cfb583cb2d4.png)

Your thoughts? :)

**Comment by ghost** [comment]
A1, C1, D1, D2

**Comment by nuagesdencre** [comment]
[SVG.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e74d40b9f140012131256/125516c66e82c728ace21e0d46dba2bd61cec1b99de6b546a749b2ce6b1325222c05a67226d7b77cbd172d515f5e18f8400c5643aeeb9539e4e76224d50152a7842f4d7ed43f10a6b9871db607ba208b4881bebc835e8d.zip)
