### ISSUE TITLE
Decide on a colour pallete

### ISSUE THREAD

**Issue by ghost** [chingu-voyage6/Geckos-Team-18-corrupted#3]

**Comment by nuagesdencre** [comment]
I found a really fun website for colour palettes.... https://coolors.co/

**Comment by nuagesdencre** [comment]
![4392f1-cbe896-fffffc-006494-f21b3f.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e74d40b9f140012131256/125516c66e82c728ace21e0d46bcc7c37184d2e48cebba1bfd0bbd922f4021752a49f37b26d1ba7cf24429500d5c18be5d4a1f06a3a3dc78e2a436628f0e0ab880385672c43915febd841fbf00ec748a1b8cb1ee9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca51f44de74a56ac173067f43b.png)
![f55d3e-ffa400-d5f2e3-878e88-ffffff.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e74d40b9f140012131256/125516c66e82c728ace21e0d46eec1cf27d186e489efbe17f40dbd907c4075767a49fb7c2880bb70f2447d07090918be5d4a1f06a3a3dc78e2a436628f0e0ab880385672c43915febd841fbf00ec748a1b8cb1ee9850d2aa6c7bb3d4d216744b470a83ed5c3daa984eca51f44de74a56ac153160f43b.png)

**Comment by ghost** [comment]
https://material.io/tools/color/#!/?view.left=1&view.right=0&secondary.color=E91E63&primary.color=4392f1

https://codepen.io/anon/pen/NzyNPY#anon-signup
