### ISSUE TITLE
Create/modify collection view

### ISSUE THREAD

**Issue by ghost** [chingu-voyage6/Geckos-Team-18-corrupted#8]
https://wireframe.cc/zdwu3P

**Comment by ghost** [comment]
Updated create collection view:
-Toolbar
-Stepper
-Name input field

**Comment by ghost** [comment]
Added add cards to your collection view:
- https://wireframe.cc/KyN6jU
- FAB button to go to create new cards view
- Select/deselect cards

**Comment by ghost** [comment]
Added change sharing settings to your collection view:
- https://wireframe.cc/mCrUW6
- Make public/private switch
- Add more people
- Change sharing settings for people

**Comment by Zefwork** [comment]
Second option for collection creating:
https://wireframe.cc/DNTgvU - one step option
